// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: proto/imp/api/websocket/websocket.proto

/*
Package gen is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package gen

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_Websocket_Subscribe_0(ctx context.Context, marshaler runtime.Marshaler, client WebsocketClient, req *http.Request, pathParams map[string]string) (Websocket_SubscribeClient, runtime.ServerMetadata, error) {
	var protoReq SubscribeRequest
	var metadata runtime.ServerMetadata

	stream, err := client.Subscribe(ctx, &protoReq)
	if err != nil {
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		return nil, metadata, err
	}
	metadata.HeaderMD = header
	return stream, metadata, nil

}

// RegisterWebsocketHandlerServer registers the http handlers for service Websocket to "mux".
// UnaryRPC     :call WebsocketServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterWebsocketHandlerFromEndpoint instead.
func RegisterWebsocketHandlerServer(ctx context.Context, mux *runtime.ServeMux, server WebsocketServer) error {

	mux.Handle("GET", pattern_Websocket_Subscribe_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		err := status.Error(codes.Unimplemented, "streaming calls are not yet supported in the in-process transport")
		_, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
		return
	})

	return nil
}

// RegisterWebsocketHandlerFromEndpoint is same as RegisterWebsocketHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterWebsocketHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterWebsocketHandler(ctx, mux, conn)
}

// RegisterWebsocketHandler registers the http handlers for service Websocket to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterWebsocketHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterWebsocketHandlerClient(ctx, mux, NewWebsocketClient(conn))
}

// RegisterWebsocketHandlerClient registers the http handlers for service Websocket
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "WebsocketClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "WebsocketClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "WebsocketClient" to call the correct interceptors.
func RegisterWebsocketHandlerClient(ctx context.Context, mux *runtime.ServeMux, client WebsocketClient) error {

	mux.Handle("GET", pattern_Websocket_Subscribe_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/websocket.Websocket/Subscribe", runtime.WithHTTPPathPattern("/v1/subscribe"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_Websocket_Subscribe_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_Websocket_Subscribe_0(ctx, mux, outboundMarshaler, w, req, func() (proto.Message, error) { return resp.Recv() }, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_Websocket_Subscribe_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"v1", "subscribe"}, ""))
)

var (
	forward_Websocket_Subscribe_0 = runtime.ForwardResponseStream
)
